# Start with a base image containing Java runtime
FROM openjdk:8-jdk-alpine

# Add Maintainer Info
LABEL maintainer='kene.prz.btz@gmail.com'

#Make port 8080 available to the world outside this container
EXPOSE 9191

# The application's jar file
ARG JAR_FILE=target/enterprise-0.0.1-SNAPSHOT.jar

# Add the application's jar to the container
ADD ${JAR_FILE} enterprise.jar

# Run the jar file
ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom","-jar","/enterprise.jar"]
